[required_files] 
FVs_biomed = '//cabinet/derivatives/DeepDR/FVs_biomed'
FVs_ConceptCLIP = '//cabinet/derivatives/DeepDR/FVs_ConceptCLIP'
FVs_CONCH = '//cabinet/derivatives/DeepDR/FVs_CONCH'
FVs_CXRCLIP = '//cabinet/derivatives/DeepDR/FVs_CXRCLIP'
FVs_DINOv2 = '//cabinet/derivatives/DeepDR/FVs_DINOv2'
FVs_EVA02-L-14-336 = '//cabinet/derivatives/DeepDR/FVs_EVA02-L-14-336'
FVs_FLAIR = '//cabinet/derivatives/DeepDR/FVs_FLAIR'
FVs_INViT-L-16 = '//cabinet/derivatives/DeepDR/FVs_INViT-L-16'
FVs_llava-med = '//cabinet/derivatives/DeepDR/FVs_llava-med'
FVs_llava-Mistral-7b = '//cabinet/derivatives/DeepDR/FVs_llava-Mistral-7b'
FVs_llava-vicuna-13b-hf = '//cabinet/derivatives/DeepDR/FVs_llava-vicuna-13b-hf'
FVs_LLM2CLIP-EVA = '//cabinet/derivatives/DeepDR/FVs_LLM2CLIP-EVA'
FVs_LLM2CLIP-openai = '//cabinet/derivatives/DeepDR/FVs_LLM2CLIP-openai'
FVs_medsiglip = '//cabinet/derivatives/DeepDR/FVs_medsiglip'
FVs_MedTrinity = '//cabinet/derivatives/DeepDR/FVs_MedTrinity'
FVs_MONET = '//cabinet/derivatives/DeepDR/FVs_MONET'
FVs_resnet50 = '//cabinet/derivatives/DeepDR/FVs_resnet50'
FVs_SigLIP = '//cabinet/derivatives/DeepDR/FVs_SigLIP'
FVs_swin = '//cabinet/derivatives/DeepDR/FVs_swin'
FVs_UNI = '//cabinet/derivatives/DeepDR/FVs_UNI'
FVs_VGG16 = '//cabinet/derivatives/DeepDR/FVs_VGG16'
FVs_ViT-B-16 = '//cabinet/derivatives/DeepDR/FVs_ViT-B-16'
FVs_ViT-g-14 = '//cabinet/derivatives/DeepDR/FVs_ViT-g-14'
FVs_ViT-L-14 = '//cabinet/derivatives/DeepDR/FVs_ViT-L-14'
[csv_files] 
RFT =  '//cabinet/data/Public_dataset/DeepDR/regular_fundus_images/regular-fundus-training/regular-fundus-training.csv'
